### PR TITLE
Fast boot 1215 working

### PR DESCRIPTION
**Pull request by wudping**
Modularize the libyami-utils code, so that yamidecode, yamiencode, yamivpp, simpleplayer and so on, can be compiled separately. It helps to reduce the size of those each application binary.

### CODE REVIEW

**Comment by wudping** [comment]
please help to review, thanks.

**Comment by wudping** [comment]
This pull-request [libyami-pull-911](https://github.com/01org/libyami/pull/819). So there is an compilation error:
09:21:43,558 INFO  - simpleplayer.cpp: In member function 'bool SimplePlayer::run()':
09:21:43,558 INFO  - simpleplayer.cpp:175:26: error: 'struct VideoConfigBuffer' has no member named 'noNeedExtraSurface'
09:21:43,558 INFO  - configBuffer.noNeedExtraSurface = true;

File: configure.ac [hunk 1]
```diff
@@ -174,6 +174,95 @@ AC_ARG_ENABLE(oclblender,
 AM_CONDITIONAL(BUILD_OCL_BLENDER,
     [test "x$enable_oclblender" = "xyes"])
 
+APPS=""
+
+dnl decoder
```
Comment (xuguangxin) [inline configure.ac]: why we need this, could we just compile all things?

File: examples/simpleplayer.cpp [hunk 2]
```diff
@@ -20,38 +20,150 @@
...
 #include <va/va_x11.h>
+#endif
+#ifdef __ENABLE_WAYLAND__
+#include <va/va_wayland.h>
+#endif
 
 using namespace YamiMediaCodec;
 
+#define CPPPRINT(...) std::cout << __VA_ARGS__ << std::endl
+#define FILE_OUTPUT 0
```
Comment (xuguangxin) [inline examples/simpleplayer.cpp]: why we need add file output, could we use yamidecode to do this?

File: examples/simpleplayer.cpp [hunk 3]
```diff
@@ -163,16 +489,123 @@ class SimplePlayer
...
     SharedPtr<IVideoDecoder> m_decoder;
     SharedPtr<DecodeInput> m_input;
     int m_width, m_height;
+    bool m_eos;
+    int m_drmFd;
+    std::ofstream m_ofs;
+    uint64_t m_frameNum;
+    SimplePlayerParameter m_parameters;
+#ifdef __ENABLE_X11__
+    SharedPtr<Display> m_display;
```
Comment (xuguangxin) [inline examples/simpleplayer.cpp]: could we have some abstract and isolate all X11/Wayland specific operation in class?

Comment (wudping) [reply examples/simpleplayer.cpp]: this code is used in fast-boot, so we try to keep the code as small as possible, and not to define classes.

File: configure.ac (hunk 1 above)
Comment (wudping) [reply configure.ac]: because libyami may not compile decoder or encoder, so we have to disable decoder in case that libyami disable all decoders. In fast-boot case, users only need decoder, so we should disable encoder and other functional code except for decoder.

**Comment by wudping** [comment]
hi @xuguangxin , all,
code are managed in classes, please help to review again.

**Comment by uartie** [comment]
Closing as inactive... please resubmit if you feel this is still relevant.
