### PR TITLE
decode avformat: av_register_all is deprecated since 58.9.100

### LINKED ISSUE #117: Compile error: av_register_all is deprecated
Compilation fails with FFMpeg master since commit https://github.com/FFmpeg/FFmpeg/commit/0694d8702421e7aff1340038559c438b61bb30dd

```
../tests/decodeinputavformat.cpp: In constructor ‘DecodeInputAvFormat::DecodeInputAvFormat()’:
../tests/decodeinputavformat.cpp:32:21: error: ‘void av_register_all()’ is deprecated [-Werror=deprecated-declarations]
     av_register_all();
                     ^
In file included from ../tests/decodeinputavformat.h:22:0,
                 from ../tests/decodeinputavformat.cpp:20:
/home/uaeoff/Work/workspace/media/install/include/libavformat/avformat.h:2024:6: note: declared here
 void av_register_all(void);
      ^~~~~~~~~~~~~~~
../tests/decodeinputavformat.cpp: In constructor ‘DecodeInputAvFormat::DecodeInputAvFormat()’:
../tests/decodeinputavformat.cpp:32:21: error: ‘void av_register_all()’ is deprecated [-Werror=deprecated-declarations]
     av_register_all();
                     ^
In file included from ../tests/decodeinputavformat.h:22:0,
                 from ../tests/decodeinputavformat.cpp:20:
/home/uaeoff/Work/workspace/media/install/include/libavformat/avformat.h:2024:6: note: declared here
 void av_register_all(void);
      ^~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [Makefile:667: ../tests/grid-decodeinputavformat.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1plus: all warnings being treated as errors
make[2]: *** [Makefile:615: ../tests/decodeinputavformat.o] Error 1
```

### PR DESCRIPTION
**Pull request by uartie**
av_register_all was deprecated in FFMPEG commit
0694d8702421e7aff1340038559c438b61bb30dd

It is no longer necessary to call av_register_all after
this commit.

Fixes #117

Signed-off-by: U. Artie Eoff <ullysses.a.eoff@intel.com>

### CODE REVIEW

**Comment by uartie** [comment]
@xuguangxin thanks for the review.  Please wait for CI builds to complete before merges in the future.
